###
SpeakEasy

## Описание

###

**SpeakEasy** — это приложение для изучения иностранных слов. Оно поддерживает:
- Многопользовательский режим
- Викторины с выбором языка
- Хранение статистики и детализированных результатов
- Работа с базой данных SQLite
- Логирование и управление пользователями
- Поддержка веб-интерфейса с использованием FastAPI
